name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        arch: [mips, mipsle, arm64]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - run: GOOS=linux GOARCH=${{ matrix.arch }} go build -o dist/kvasx-${{ matrix.arch }} ./cmd/kvasx
      - uses: actions/upload-artifact@v4
        with:
          name: kvasx-${{ matrix.arch }}
          path: dist/kvasx-${{ matrix.arch }}
